import { Component, OnInit } from '@angular/core';
import { AuditTrailService } from '../../core/services/audit-trail.service';
import { RealtimeService } from '../../core/services/realtime.service';
import { AuditLog } from '../../core/models/audit-log.model';

/**
 * Component for displaying the history of synchronization events between environments.
 * Provides a live view of sync logs as they are generated by the backend.
 */
@Component({
  selector: 'app-audit-trail',
  templateUrl: './audit-trail.component.html',
  styleUrls: ['./audit-trail.component.scss']
})
export class AuditTrailComponent implements OnInit {
  /** List of audit logs to display in the UI */
  auditLogs: AuditLog[] = [];

  constructor(
    private auditTrailService: AuditTrailService,
    private realtimeService: RealtimeService
  ) {}

  /**
   * Initializes the component by fetching historical logs and subscribing to real-time sync updates.
   */
  ngOnInit(): void {
    this.auditTrailService.getAuditLogs().subscribe(logs => {
      this.auditLogs = logs;
    });

    // Prepend new sync logs to the list in real-time
    this.realtimeService.getUpdates().subscribe(update => {
      if (update && update.entityName) {
        this.auditLogs = [update, ...this.auditLogs];
      }
    });
  }
}
